# ╔══════════════════════════════════════════════╗
# ║         CrossRealmMC - config.yml            ║
# ║     Hecho por soyadrianyt001                 ║
# ╚══════════════════════════════════════════════╝

server:
  java-ip: "127.0.0.1"
  java-port: 25565
  bedrock-ip: "0.0.0.0"
  bedrock-port: 19132
  motd-line1: "&bCrossRealmMC &7| Java + Bedrock"
  motd-line2: "&aConecta desde cualquier edicion!"
  max-bedrock-players: 0

authentication:
  java-online-mode: true
  bedrock-online-mode: false
  bedrock-prefix: "."

bedrock-versions:
  - "26.3"

language: "es"

whitelist:
  bedrock-whitelist: false
  java-whitelist: false

anticheat:
  enabled: true
  check-movement: true
  check-speed: true
  action: "KICK"
  kick-message: "&cFuiste expulsado por movimiento invalido."

reconnect-cooldown:
  enabled: true
  seconds: 5

logging:
  enabled: true
  file: "plugins/CrossRealmMC/logs/connections.txt"
  log-bedrock-join: true
  log-java-join: false
  log-disconnect: true

debug: false

auto-restart:
  enabled: true
  delay-seconds: 10

chat:
  show-edition-prefix: true
  java-prefix: "&7[&aJava&7]"
  bedrock-prefix: "&7[&bBedrock&7]"
