server:
  java-ip: "127.0.0.1"
  java-port: 26573
  bedrock-ip: "0.0.0.0"
  bedrock-port: 26573
  motd-line1: "&bCrossRealmMC &7| Java + Bedrock"
  motd-line2: "&aConecta desde cualquier edicion!"

online-mode: false

bedrock-versions:
  - "26.10"

debug: true
